### ISSUE TITLE
option to specify editor

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-viewer#2]
currently, it shows 

![viewer-editor](https://user-images.githubusercontent.com/56868/66105715-74574700-e5bc-11e9-8f4e-c35adf1f33e0.png)

even after ticking "use external editor" in Options, and then opens the t1x in Firefox …

It'd be very nice if we could specify e.g. 

`/usr/bin/emacsclient +%n %s` 

and then it would open `/usr/bin/emacsclient +714 '/home/me/Some Directory/foo.t1x'`  when you clicked on "rule 14" in the apertium-transfer trace (since rule 14 is on line 714).

(Or `/path/to/subl %s:%n` would turn into  `/path/to/subl '/home/me/Some Directory/foo.t1x:714'`  for [sublime](https://stackoverflow.com/a/48804739/69663) etc.)

**Comment by nordfalk** [comment]
Done!

http://wiki.apertium.org/wiki/Apertium-viewer#Version_2.5.5_.28oct_2019.29

**Comment by unhammer** [comment]
works, thanks =D
